# main text of home
name: Aman Goyal
bio: A Man who never has enough time

# twitter summary info
description: Aman Goyal blogs about technology and related stuff here. He tries to play FPS games like CSGO, Valorant on his potato pc, which he also uses to code. A passionate quizzer and a fervent reader(mainly light novels and mangas)

# if it's an external image, update below for true
# better with square images
external-image: false
# picture: assets/images/profile.jpg
picture: assets/images/placeholder-profile-male-500x500-min.png

# If you want to include your resume, set to true
# and specify source (external or local).
resume: false
resume-external: false
resume-url: None

url: https://amangoyal.me
# your url: https://USERNAME.github.io

permalink: /:slug/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
# disqus:
#   shortname: mydisqus # enter this from your disqus account
#   categories: [blog, project] # only show disqus for posts that have these categories

social:
  name: Aman Goyal
  links:
    - https://twitter.com/a_man_goyal
    - https://www.linkedin.com/in/-amangoyal
    - https://github.com/aman-1412

webmaster_verifications:
  google: XMDdOzBjUIrZJZCKFNYauXrjgrgcr7s3qzGFHTJcnIg

# if you don't have any of social below, comment the line
# facebook: myfacebook
twitter: 
  username: a_man_goyal
  card: summary
# instagram: myinstagram
# pinterest: mypinterest
linkedin: https://www.linkedin.com/in/-amangoyal
# youtube: myyoutube
# spotify: myspotify
github: Aman-1412
# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
email: goyal.amanr@gmail.com

# Pro-tip: If authors is present in the document's front matter as an array (and author is not), the plugin will use the first author listed, as Twitter supports only one author.
authors:
  aman:
    name: Aman Goyal
    bio: A Man who never has enough time
    description: A blog about technology and related stuff
    external-image: false
    picture: assets/images/placeholder-profile-male-500x500-min.png
    twitter: a_man_goyal
  sherlock:
    name: Sherlock Holmes
    bio: A Man's alter ego
    external-image: false
    picture: assets/images/profile.jpg
    twitter: sholmes
  jamesfoster:
    name: James Foster
    bio: A Man who develops software with coffee
    external-image: false
    picture: assets/images/james.jpg
    twitter: jamesfoster

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

locale: en-US

# if you do/don't need pagination, toggle 'enabled' between true/false below
pagination:
  enabled: true
  sort_reverse: true # display recent posts first
  title: ":title" # Changing this will mess up the header display logic
  per_page: 5
  permalink: "/:num/" # pagination link that will be appended

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

# add default values to specific pages or layouts
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      layout: "post"
    values:
      # setting all post to not hidden by default,
      # can be overridden in the front matter for a specific post
      hidden: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
  - jekyll-paginate-v2
  - jekyll-sitemap

jekyll-mentions:
  base_url: https://github.com

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "travis.sh",
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor",
  ]
